import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
} from "@material-ui/core";
import Head from "next/head";
import Image from "next/image";
import { getUsers } from "../api/getUser";
import styles from "../styles/Home.module.css";

export default function Home(props) {
  const { data } = props;
  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>users</h1>

        <Table>
          <TableHead>
            <TableRow>
              <TableCell>#</TableCell>
              <TableCell>username</TableCell>
              <TableCell>email</TableCell>
              <TableCell>phone</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {data.map((v, i) => (
              <TableRow key={i}>
                <TableCell>{v.id}</TableCell>
                <TableCell>{v.username}</TableCell>
                <TableCell>{v.email}</TableCell>
                <TableCell>{v.phone}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await getUsers();
  return {
    props: { data: res }, // will be passed to the page component as props
  };
};
